Repository lincity-ng/lincity-ng, pull requests merged in 2024-11, with the labels that each got.

#204 Stop merge conflicts in CHANGELOG.md
  CHANGELOG.d/apply-changelog.sc
  CHANGELOG.d/fix-changelog-conflicts.md
  CHANGELOG.d/template.md
Labels: enhancement

#207 fixup after #173
  data/CMakeLists.txt
Labels: bug

#214 Local physfsrwops
  CMakeLists.txt
  external/CMakeLists.txt
  external/physfsrwops/CMakeLists.txt
  external/physfsrwops/physfsrwops.c
  external/physfsrwops/physfsrwops.h
  src/PhysfsStream/CMakeLists.txt
Labels: critical, portability

#208 cleanup some duplicates files
  data/help/ru/keys.xml
  data/sounds/ElectricityNoise.wav
  data/sounds/Seagulls.wav
  data/sounds/Tip2.wav
  data/sounds/TruckEngine.wav
  data/sounds/Water2.wav
  data/sounds/WindMillHTech1.wav
  data/sounds/sounds.xml
Labels: housekeeping

#213 fix trailing space in xmlgettext
  src/tools/xmlgettext/main.cpp
Labels: bug
