Repository lincity-ng/lincity-ng, pull requests merged in 2025-07, with the labels that each got.

#265 fix missing button panel tooltips
  src/gui/CheckButton.cpp
  src/gui/CheckButton.hpp
  src/lincity-ng/ButtonPanel.cpp
Labels: bug

#266 fix memory leaks from gui paragraphs
  CHANGELOG.d/fix-mem-leak.md
  src/gui/Paragraph.cpp
  src/gui/Paragraph.hpp
Labels: bug

#267 fix query on right-click when the MPS display is not already selected
  src/lincity-ng/GameView.cpp
Labels: bug

#271 remove hack preventing libxml2 from overlinking
  CMakeLists.txt
Labels: housekeeping

#277 Add appstream metainfo and related content
  CHANGELOG.d/appstream-metainfo.md
  CMakeLists.txt
  contrib/screenshots/screenshot-1.png
  contrib/screenshots/screenshot-2.png
  contrib/screenshots/screenshot-3.png
  data/CMakeLists.txt
  data/io.github.lincity_ng.lincity-ng.desktop
  data/io.github.lincity_ng.lincity-ng.metainfo.xml
  data/io.github.lincity_ng.lincity-ng.png
  data/io.github.lincity_ng.lincity-ng_2x.png
Labels: portability

#282 Use presice scrolling where applicable
  CHANGELOG.d/precise-scrolling.md
  src/gui/Event.cpp
  src/gui/Event.hpp
  src/gui/ScrollView.cpp
Labels: enhancement

#278 fix strange texture sampling by rounding texture translation
  CHANGELOG.d/fix-image-sampling.md
  CHANGELOG.md
  src/gui/Image.cpp
  src/gui/PainterSDL/PainterSDL.cpp
Labels: bug
